common: Include sys/types.h header
Build with musl library fails with following error:

In file included from src/crypto/sha1.c:21:0:
./src/digest.h:95:10: error: unknown type name ‘ulong’
          ulong start, ulong size);
...

Fix that by including sys/types.h header in common.h, so ulong type
is defined with musl library.

Signed-off-by: Marcin Niestroj <m.niestroj@grinn-global.com>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>